'use client';
import Image from "next/image";
import {useOramaRows} from "@webdock/search/react";
import { msgid } from '@webdock/i18n';

import { useI18n } from '@webdock/i18n/react';

import {useActionState,useCallback,useEffect,useRef,useState,type ReactNode} from 'react';
import type {ShopProduct,ShopContent,ShopMedia,ShopCustomer,ShopAddress} from '@/lib/studio-shop';
import {saveShop} from './actions';
type EditorStatus={dirty:boolean;pending:boolean};
type StatusHandler=(status:EditorStatus)=>void;
const money=(n:number,locale:string)=>new Intl.NumberFormat(locale,{style:'currency',currency:'EUR'}).format(n/100);
const categories:Record<string,string>={pizza:msgid("Pizza"),burger:msgid("Burger"),sides:msgid("Sides"),drinks:msgid("Drinks"),dessert:msgid("Dessert")};
const defaultTags:Record<string,string>={vegetarisch:msgid("Vegetarian"),vegan:msgid("Vegan"),scharf:msgid("Spicy"),favorit:msgid("Favourite")};
const sectionNames:Record<string,string>={homepage:msgid("Homepage"),'site-settings':msgid("Business & contact"),promotion:msgid("Daily promotion")};
const labels:Record<string,string>={headline:msgid("Headline"),intro:msgid("Introduction"),featureTitle:msgid("Featured products heading"),featureCopy:msgid("Featured products text"),name:msgid("Business name"),phone:msgid("Phone"),street:msgid("Street"),city:msgid("City"),hours:msgid("Opening hours"),notice:msgid("Notice"),title:msgid("Promotion title"),startsOn:msgid("Valid from"),endsOn:msgid("Valid until"),heroImage:msgid("Homepage image"),featuredProducts:msgid("Featured products")};
function useEdit(initialVersion:string,onStatus?:StatusHandler){
 const [dirty,setDirty]=useState(false);const [version,setVersion]=useState(initialVersion);
 // A remote revalidation must never authorize an old draft against somebody else's version.
 const [state,action,pending]=useActionState(async(previous:{error?:string;message?:string;updatedAt?:string},form:FormData)=>{
  const result=await saveShop(previous,form);
  if(result.message&&result.updatedAt){setDirty(false);setVersion(result.updatedAt);}
  return result;
 },{});
 useEffect(()=>{onStatus?.({dirty,pending})},[dirty,pending,onStatus]);
 useEffect(()=>()=>onStatus?.({dirty:false,pending:false}),[onStatus]);
 return {state,action,pending,dirty,version,changed:()=>setDirty(true)};
}
function useSelection(){
  const i18n = useI18n();

 const [selected,setSelected]=useState<string|null>(null);const [status,setStatus]=useState<EditorStatus>({dirty:false,pending:false});
 const onStatus=useCallback((next:EditorStatus)=>setStatus(prev=>prev.dirty===next.dirty&&prev.pending===next.pending?prev:next),[]);
 const mayLeave=useCallback(()=>{if(status.pending){window.alert(i18n.t("The change is being saved. Please wait."));return false;}return !status.dirty||window.confirm(i18n.t("Discard unsaved changes?"));},[status,i18n]);
 useEffect(()=>{
  const beforeUnload=(e:BeforeUnloadEvent)=>{if(status.dirty||status.pending){e.preventDefault();e.returnValue='';}};
  const navigate=(e:MouseEvent)=>{if(e.defaultPrevented||e.button!==0||e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;const a=(e.target as Element)?.closest?.('a[href]');if(!(a instanceof HTMLAnchorElement)||a.target==='_blank'||a.hasAttribute('download'))return;const destination=new URL(a.href,location.href);if(destination.href===location.href||(destination.pathname===location.pathname&&destination.search===location.search&&destination.hash))return;if(!mayLeave()){e.preventDefault();e.stopImmediatePropagation();}};
  window.addEventListener('beforeunload',beforeUnload);document.addEventListener('click',navigate,true);
  return()=>{window.removeEventListener('beforeunload',beforeUnload);document.removeEventListener('click',navigate,true);};
 },[status,mayLeave]);
 const select=(id:string|null)=>{if(id===selected||!mayLeave())return;setStatus({dirty:false,pending:false});setSelected(id)};
 return {selected,select,onStatus,status};
}
function revealInvalidField(target:EventTarget){let detail=(target as Element).closest('details');while(detail){detail.open=true;detail=detail.parentElement?.closest('details')||null;}}
function Feedback({state,pending,dirty}:{state:{error?:string;message?:string};pending:boolean;dirty:boolean}){
  const i18n = useI18n();
return <div className="cms-savebar shop-savebar"><div>{state.error?<p role="alert" className="shop-error">{i18n.error(state.error)}</p>:<p role="status" className={dirty?'shop-changed':''}>{pending?i18n.t("Saving change…"):dirty?i18n.t("Unsaved changes"):state.message?i18n.t("Saved · visible on the website"):i18n.t("No unsaved changes")}</p>}</div><button className="button" disabled={pending||!dirty}>{pending?i18n.t("Saving…"):i18n.t("Save")}</button></div>;}
function FormSection({title,children,open=false,description}:{title:string;children:ReactNode;open?:boolean;description?:string}){return <details className="shop-form-section" open={open}><summary>{title}{description&&<span>{description}</span>}</summary><div className="shop-section-fields">{children}</div></details>;}
function DetailPanel({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){
  const i18n = useI18n();
const ref=useRef<HTMLElement>(null);useEffect(()=>{if(window.matchMedia('(max-width: 767px)').matches){ref.current?.focus();ref.current?.scrollIntoView({block:'start'});}},[title]);return <section ref={ref} tabIndex={-1} className="cms-panel shop-detail" aria-label={title}><header className="shop-detail-heading"><div><button type="button" className="shop-back" onClick={onClose}>{i18n.t("← Back to list")}</button><h2>{title}</h2></div><button type="button" className="shop-close" onClick={onClose} aria-label={i18n.t("Close editor")}>×</button></header>{children}</section>;}
function EmptyDetail(){
  const i18n = useI18n();
return <div className="cms-panel shop-select-hint"><span>{i18n.t("Select an entry")}</span><p>{i18n.t("View and edit the details.")}</p></div>;}
export function ProductWorkspace({bindingID,products,media=[],imageOrigin,writable,categoryOptions=categories,tagOptions=defaultTags}:{bindingID:string;products:ShopProduct[];categoryOptions?:Record<string,string>;tagOptions?:Record<string,string>;media?:ShopMedia[];imageOrigin:string;writable:boolean}){
  const i18n = useI18n();

 const [query,setQuery]=useState('');const edit=useSelection();const selected=products.find(p=>String(p.id)===edit.selected);const filtered=useOramaRows(products,query,p=>[p.name,p.description,categoryOptions[p.category]].join(' '));
 return <div className={'shop-workspace '+(selected?'has-selection':'')}><section className="cms-panel shop-index" aria-label={i18n.t("Product list")}><div className="shop-toolbar"><label className="shop-search"><span className="shop-sr-only">{i18n.t("Search products on this page")}</span><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder={i18n.t("Search products…")}/></label><span className="shop-count">{filtered.length} / {products.length}</span></div><div className="shop-list-labels" aria-hidden="true"><span>{i18n.t("Product")}</span><span>{i18n.t("Price from")}</span><span>{i18n.t("Status")}</span></div><div className="shop-rows">{filtered.map(p=><button type="button" key={p.id} className={'shop-row '+(selected?.id===p.id?'is-selected':'')} aria-pressed={selected?.id===p.id} onClick={()=>edit.select(String(p.id))}><span className="shop-row-name"><strong>{p.name}</strong><small>{i18n.t(categoryOptions[p.category]||p.category)}</small></span><span className="shop-row-price">{p.variants.length?money(Math.min(...p.variants.map(v=>v.price)), i18n.locale):'—'}</span><span className={'shop-status '+(p.available?'is-active':'')}>{p.available?i18n.t("Available"):i18n.t("Paused")}</span></button>)}</div>{!filtered.length&&<p className="shop-empty">{i18n.t("No products match this search.")}</p>}<p className="shop-index-note">{i18n.t("Search the products on this page.")}</p></section>
 {selected?<DetailPanel title={selected.name} onClose={()=>edit.select(null)}>{writable?<ProductForm key={selected.id} bindingID={bindingID} product={selected} categoryOptions={categoryOptions} tagOptions={tagOptions} media={media} imageOrigin={imageOrigin} onStatus={edit.onStatus}/>:<div className="shop-readonly"><p>{selected.description}</p><dl>{selected.variants.map(v=><div key={v.key}><dt>{v.label}</dt><dd>{money(v.price, i18n.locale)}</dd></div>)}</dl><p className="shop-help">{i18n.t("Read access")}</p></div>}</DetailPanel>:<EmptyDetail/>}</div>;
}
export function ProductForm({bindingID,product:p,media=[],imageOrigin,onStatus,categoryOptions=categories,tagOptions=defaultTags}:{bindingID:string;product:ShopProduct;categoryOptions?:Record<string,string>;tagOptions?:Record<string,string>;media?:ShopMedia[];imageOrigin:string;onStatus?:StatusHandler}){
  const i18n = useI18n();

 const edit=useEdit(p.updatedAt,onStatus);
 return <form action={edit.action} onReset={e=>e.preventDefault()} onChange={edit.changed} onInvalidCapture={e=>revealInvalidField(e.target)} className="shop-form"><fieldset className="shop-form-body" disabled={edit.pending}><input type="hidden" name="bindingID" value={bindingID}/><input type="hidden" name="kind" value="products"/><input type="hidden" name="id" value={p.id}/><input type="hidden" name="updatedAt" value={edit.version}/>
 <FormSection title={i18n.t("Product details")} open><label>{i18n.t("Product name")}<input name="name" defaultValue={p.name} required maxLength={120}/></label><label>{i18n.t("Description")}<textarea name="description" defaultValue={p.description} required maxLength={2000} rows={3}/></label><div className="shop-fields"><label>{i18n.t("Category")}<select name="category" defaultValue={p.category}>{Object.entries(categoryOptions).map(([key,label])=><option key={key} value={key}>{i18n.t(label)}</option>)}</select></label><label>{i18n.t("Order")}<input type="number" name="sort" min="0" max="10000" defaultValue={p.sort}/></label></div><label className="shop-check"><input type="checkbox" name="available" defaultChecked={p.available}/>{i18n.t("Available in the shop")}</label><div className="shop-tags" role="group" aria-label={i18n.t("Properties")}>{Object.keys(tagOptions).map(tag=><label className="shop-check" key={tag}><input type="checkbox" name="tags" value={tag} defaultChecked={p.tags.includes(tag)}/>{i18n.t(tagOptions[tag]||tag)}</label>)}</div></FormSection>
 {(['variants','extras'] as const).map(name=><FormSection key={name} title={name==='variants'?i18n.t("Variants & prices"):i18n.t("Product extras")} description={String(p[name].length)} open={name==='variants'}><input type="hidden" name={name+'Count'} value={p[name].length}/>{!p[name].length&&<p className="shop-help">{i18n.t("No extras configured.")}</p>}{p[name].map((v,i)=><div className="shop-fields" key={v.key}><input type="hidden" name={name+i+'id'} value={v.id}/><input type="hidden" name={name+i+'key'} value={v.key}/><label>{i18n.t("Label")}<input name={name+i+'label'} defaultValue={v.label} required maxLength={100}/></label><label>{i18n.t("Price in €")}<input name={name+i+'price'} type="number" step="0.01" min="0" max={name==='variants'?1000:100} defaultValue={(v.price/100).toFixed(2)} required/></label></div>)}<p className="shop-help">{i18n.t("Existing assignments are preserved.")}</p></FormSection>)}
 <FormSection title={i18n.t("Product image")} description={p.photo?i18n.t("Media image"):i18n.t("Image URL")}><ImageField value={p.image} origin={imageOrigin}/><MediaPicker name="photo" label={i18n.t("Product photo from media")} value={p.photo} media={media}/><p className="shop-help">{i18n.t("The media photo takes precedence over the image URL.")}</p></FormSection>
 </fieldset><Feedback {...edit}/></form>;
}
function imageURL(value:string,origin=''){if(value==='none'||!value)return '';if(/^\/[a-zA-Z0-9/_.-]+$/.test(value)&&!value.split('/').slice(1).some(p=>!p||p==='.'||p==='..'))return origin+value;try{const u=new URL(value);if(u.protocol==='https:'&&!u.username&&!u.password&&!/\s|\\/.test(value))return value;}catch{}return '';}
function ImageField({value,origin}:{value:string;origin:string}){
  const i18n = useI18n();
const [image,setImage]=useState(value);const url=imageURL(image,origin);return <div className="shop-image-control"><label>{i18n.t("Image URL")}<input name="image" value={image} onChange={e=>setImage(e.target.value)} required maxLength={2000}/></label><p className="shop-help">{i18n.t("Local path or HTTPS URL. “none” means no fallback image.")}</p>{url&&<Image unoptimized width={320} height={240} className="shop-image-preview" src={url} alt={i18n.t("Preview of the product image URL")} referrerPolicy="no-referrer"/>}</div>;}
function MediaPicker({name,label,value,media}:{name:string;label:string;value:number|null;media:ShopMedia[]}){
  const i18n = useI18n();
const [selected,setSelected]=useState(value?String(value):'');const current=media.find(m=>String(m.id)===selected);return <div className="shop-image-control"><label>{label}<select name={name} value={selected} onChange={e=>setSelected(e.target.value)}><option value="">{i18n.t("Do not use media")}</option>{value&&!media.some(m=>m.id===value)&&<option value={value}>{i18n.t("Current selection #")}{value}</option>}{media.map(m=><option key={m.id} value={m.id}>{m.alt||i18n.t("Image")} · #{m.id}</option>)}</select></label>{current&&imageURL(current.url)&&<Image unoptimized width={320} height={240} className="shop-image-preview" src={current.url} alt={current.alt||i18n.t("Media preview")} referrerPolicy="no-referrer"/>}{!media.length&&<p className="shop-help">{i18n.t("No media yet. Select existing images here.")}</p>}</div>;}
export function SettingsWorkspace({bindingID,sections,media=[],products=[],writable}:{bindingID:string;sections:ShopContent[];media?:ShopMedia[];products?:{id:number;name:string}[];writable:boolean}){
  const i18n = useI18n();

 const edit=useSelection();const selected=sections.find(s=>s.section===edit.selected);const descriptions:Record<string,string>={homepage:msgid("Text, hero image and featured products"),'site-settings':msgid("Address, contact details and opening hours"),promotion:msgid("Dates and offer in the demo cart")};
 return <div className={'shop-workspace shop-settings-workspace '+(selected?'has-selection':'')}><section className="cms-panel shop-index" aria-label={i18n.t("Content areas")}>{sections.map(s=><button key={s.section} type="button" className={'shop-section-row '+(s.section===edit.selected?'is-selected':'')} aria-pressed={s.section===edit.selected} onClick={()=>edit.select(s.section)}><span><strong>{i18n.t(sectionNames[s.section])}</strong><small>{i18n.t(descriptions[s.section])}</small></span><span className="shop-row-end">{s.section==='promotion'?(s.data.enabled?i18n.t("Active"):i18n.t("Inactive")):(writable?i18n.t("Edit"):i18n.t("View"))} <span aria-hidden="true">›</span></span></button>)}</section>{selected?<DetailPanel title={i18n.t(sectionNames[selected.section])} onClose={()=>edit.select(null)}>{writable?<ContentForm key={selected.section} bindingID={bindingID} content={selected} media={media} products={products} onStatus={edit.onStatus}/>:<div className="shop-readonly"><dl>{Object.entries(selected.data).map(([key,value])=><div key={key}><dt>{i18n.t(labels[key]||key)}</dt><dd>{Array.isArray(value)?value.map(id=>products.find(p=>p.id===id)?.name||'#'+id).join(', '):typeof value==='boolean'?(value?i18n.t("Active"):i18n.t("Inactive")):String(value??i18n.t("Not selected"))}</dd></div>)}</dl><p className="shop-help">{i18n.t("Read access")}</p></div>}</DetailPanel>:<EmptyDetail/>}</div>;
}
export function ContentForm({bindingID,content,media=[],products=[],onStatus}:{bindingID:string;content:ShopContent;media?:ShopMedia[];products?:{id:number;name:string}[];onStatus?:StatusHandler}){
  const i18n = useI18n();

 const edit=useEdit(content.updatedAt,onStatus);const picks=Array.isArray(content.data.featuredProducts)?content.data.featuredProducts:[];
 return <form action={edit.action} onReset={e=>e.preventDefault()} onChange={edit.changed} onInvalidCapture={e=>revealInvalidField(e.target)} className="shop-form"><fieldset className="shop-form-body" disabled={edit.pending}><input type="hidden" name="bindingID" value={bindingID}/><input type="hidden" name="kind" value="settings"/><input type="hidden" name="section" value={content.section}/><input type="hidden" name="updatedAt" value={edit.version}/>
 <div className="shop-section-fields">{Object.entries(content.data).filter(([key])=>!['heroImage','featuredProducts'].includes(key)).map(([key,value])=>key==='enabled'?<label key={key} className="shop-check"><input type="checkbox" name={key} defaultChecked={!!value}/>{i18n.t("Daily promotion enabled")}</label>:<label key={key}>{i18n.t(labels[key]||key)}{['intro','featureCopy','notice','headline','featureTitle'].includes(key)?<textarea name={key} rows={['headline','featureTitle'].includes(key)?2:3} maxLength={['intro','featureCopy','notice'].includes(key)?2000:300} defaultValue={String(value)}/>:<input name={key} type={['startsOn','endsOn'].includes(key)?'date':'text'} maxLength={key==='title'?80:300} defaultValue={String(value)}/>}</label>)}</div>
 {content.section==='homepage'&&<><FormSection title={i18n.t("Homepage image")}><MediaPicker name="heroImage" label={i18n.t("Existing media")} value={typeof content.data.heroImage==='number'?content.data.heroImage:null} media={media}/></FormSection><FormSection title={i18n.t("Featured products")} description={picks.length+' / 4'}><input type="hidden" name="featuredProductsPresent" value="1"/><p className="shop-help">{i18n.t("Select up to four products in the desired order. Select each product only once.")}</p>{Array.from({length:4},(_,i)=><label key={i}>{i18n.t("Place ")}{i+1}<select name="featuredProducts" defaultValue={picks[i]||''}><option value="">{i18n.t("No product")}</option>{picks[i]&&!products.some(p=>p.id===picks[i])&&<option value={picks[i]}>{i18n.t("Current product #")}{picks[i]}</option>}{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>)}</FormSection></>}
 </fieldset><Feedback {...edit}/></form>;
}
export function CustomerWorkspace({bindingID,customers,writable}:{bindingID:string;customers:ShopCustomer[];writable:boolean}){
  const i18n = useI18n();

 const edit=useSelection();const [query,setQuery]=useState('');const selected=customers.find(c=>String(c.id)===edit.selected);const filtered=useOramaRows(customers,query,c=>c.name+' '+c.email);
 return <div className={'shop-workspace '+(selected?'has-selection':'')}><section className="cms-panel shop-index" aria-label={i18n.t("Customer list")}><div className="shop-toolbar"><label className="shop-search"><span className="shop-sr-only">{i18n.t("Search customers on this page")}</span><input type="search" placeholder={i18n.t("Search name or email…")} value={query} onChange={e=>setQuery(e.target.value)}/></label><span className="shop-count">{filtered.length}</span></div>{filtered.map(c=><button key={c.id} type="button" className={'shop-section-row '+(selected?.id===c.id?'is-selected':'')} aria-pressed={selected?.id===c.id} onClick={()=>edit.select(String(c.id))}><span><strong>{c.name}</strong><small>{c.email}</small></span><span className="shop-row-end">{c.verified?i18n.t("Verified"):i18n.t("Pending")} <span aria-hidden="true">›</span></span></button>)}{!filtered.length&&<p className="shop-empty">{i18n.t("No matching customers.")}</p>}</section>{selected?<DetailPanel title={selected.name} onClose={()=>edit.select(null)}><div className="shop-customer-meta"><span>{selected.email}</span><span>{selected.verified?i18n.t("Email verified"):i18n.t("Verification pending")}</span></div>{writable?<CustomerForm key={selected.id} bindingID={bindingID} customer={selected} onStatus={edit.onStatus}/>:<div className="shop-readonly"><h3>{i18n.t("Addresses")}</h3>{selected.addresses.length?selected.addresses.map((address,index)=><p key={index}><strong>{address.label||i18n.t("Address {number}",{number:index+1})}</strong><br/>{address.street}<br/>{address.postalCode} {address.city}</p>):<p>{i18n.t("No addresses saved.")}</p>}<p className="shop-help">{i18n.t("Read access")}</p></div>}</DetailPanel>:<EmptyDetail/>}</div>;
}
export function CustomerForm({bindingID,customer:c,onStatus}:{bindingID:string;customer:ShopCustomer;onStatus?:StatusHandler}){
  const i18n = useI18n();

 const edit=useEdit(c.updatedAt,onStatus);const [addresses,setAddresses]=useState<(ShopAddress&{rowKey:number})[]>(c.addresses.map((a,i)=>({...a,rowKey:i})));const [nextKey,setNextKey]=useState(c.addresses.length);
 return <form action={edit.action} onReset={e=>e.preventDefault()} onChange={edit.changed} onInvalidCapture={e=>revealInvalidField(e.target)} className="shop-form"><fieldset className="shop-form-body" disabled={edit.pending}><input type="hidden" name="bindingID" value={bindingID}/><input type="hidden" name="kind" value="customers"/><input type="hidden" name="id" value={c.id}/><input type="hidden" name="updatedAt" value={edit.version}/><input type="hidden" name="addressCount" value={addresses.length}/><div className="shop-section-fields"><label>{i18n.t("Name")}<input name="name" defaultValue={c.name} required maxLength={120}/></label></div>
 {addresses.map((a,i)=><FormSection title={a.label||i18n.t("Address {number}",{number:i+1})} key={a.rowKey} open>{(['label','street','postalCode','city'] as const).map(key=><label key={key}>{i18n.t(({label:msgid("Label"),street:msgid("Street and number"),postalCode:msgid("Postal code"),city:msgid("City")})[key])}<input name={'address'+i+key} defaultValue={a[key]} required={key!=='label'} maxLength={({label:60,street:160,postalCode:10,city:100})[key]}/></label>)}<button type="button" className="shop-text-button" onClick={()=>{edit.changed();setAddresses(rows=>rows.filter(row=>row.rowKey!==a.rowKey));}}>{i18n.t("Remove address")}</button></FormSection>)}
 <div className="shop-section-fields">{addresses.length<5&&<button type="button" className="button secondary" onClick={()=>{edit.changed();setAddresses(rows=>[...rows,{rowKey:nextKey,label:'',street:'',postalCode:'',city:''}]);setNextKey(k=>k+1)}}>{i18n.t("Add address")}</button>}<p className="shop-help">{i18n.t("Only name and addresses are changed. Credentials remain protected; no email is sent.")}</p></div></fieldset><Feedback {...edit}/></form>;
}
