import fs from 'node:fs';import path from 'node:path';import {parseEnv} from 'node:util';import {Pool} from 'pg';
const root=path.resolve(process.cwd(),'../../..');const owner=parseEnv(fs.readFileSync(path.join(root,'webdock-cms/.env.local'),'utf8'));const runtime=parseEnv(fs.readFileSync('.env.instance','utf8'));
Object.assign(process.env,runtime,{DATABASE_URL:owner.DATABASE_URL,DATABASE_URL_UNPOOLED:owner.DATABASE_URL_UNPOOLED,NEXT_PUBLIC_SERVER_URL:'https://studio.webdock.dev'});for(const key of Object.keys(process.env))if(key.startsWith('SMTP_'))delete process.env[key];
const {getPayload}=await import('payload');const {default:config}=await import('../src/payload.config.ts');const {writeCustomer,writeProject,writeInstance}=await import('../src/lib/registry.ts');const {closeSnowflakePool}=await import('../src/lib/snowflake.ts');
const payload=await getPayload({config});const db=new Pool({connectionString:owner.DATABASE_URL_UNPOOLED||owner.DATABASE_URL});const out=path.join(root,'webdock-demos/food-showcase-registry.json');const reg=fs.existsSync(out)?JSON.parse(fs.readFileSync(out,'utf8')):{};const id='WD-SHOWCASE-FOOD-NORDLICHT',entry=reg[id]||{};const save=()=>fs.writeFileSync(out,JSON.stringify({...reg,[id]:entry},null,2)+'\n');
try{
const operator=(await payload.find({collection:'users',where:{email:{equals:'dominik@spitzli.dev'}},limit:1,overrideAccess:true})).docs[0];if(operator?.role!=='operator')throw Error('Operator not found');const actor={payload,user:{...operator,collection:'users' as const}};
if(!entry.customerID){const found=await payload.find({collection:'customers',where:{name:{equals:'Nordlicht Küche · fiktiver Lieferdienst'}},overrideAccess:true});if(found.totalDocs)throw Error('Existing showcase customer without local receipt');const c=await writeCustomer(actor,null,{name:'Nordlicht Küche · fiktiver Lieferdienst',customerType:'company',companyName:'Nordlicht Küche – fiktiver Musterlieferdienst',contactEmail:'nordlicht-kueche@example.invalid',country:'DE',notes:'Fiktiver deutschsprachiger Webdock-Testmandant. Keine echten Kundendaten, keine Einladungen, kein Mailversand und keine Zahlungen. Separater Showcase außerhalb der 15 Lead-Demos.'});entry.customerID=c.id;save();}
entry.tenantID=(await db.query('SELECT organization_id FROM webdock_auth.tenant_customer WHERE customer_id=$1',[entry.customerID])).rows[0]?.organization_id;if(!entry.tenantID)throw Error('Tenant trigger did not run');save();
if(!entry.projectID){const p=await writeProject(actor,null,{name:'Nordlicht Küche – deutscher Demo-Shop',customer:entry.customerID,url:'https://nordlicht-kueche.webdock.dev',notes:'Fiktiver Lieferdienst mit Produkten, Varianten, Extras, Warenkorb und ausschließlich simulierten Bestellungen. Eigenständiger Showcase, keine Lead-Vertriebszuordnung.'});entry.projectID=p.id;save();}
if(process.argv.includes('--binding')&&!entry.instanceID){const host=JSON.parse(fs.readFileSync(path.join(root,'webdock-demos/sites/nordlicht-kueche/.vercel/project.json'),'utf8'));const b=await writeInstance(actor,null,{project:entry.projectID,label:'Nordlicht Küche · Shop & Produktverwaltung',adminURL:'https://nordlicht-kueche.webdock.dev/admin',schemaName:'nordlicht_kueche',providerProjectID:host.projectId,provider:'vercel',template:'custom',payloadVersion:'4.0.0-canary.37',status:'active',notes:'Fiktiver Testbetrieb: deutscher Demo-Shop, Produktverwaltung, Medien, Varianten, Extras und simulierte Bestellungen. Kein Versand, keine Bezahlung.'},true);entry.instanceID=b.id;entry.url='https://nordlicht-kueche.webdock.dev';entry.vercelProjectID=host.projectId;save();}if(process.argv.includes('--link-cms'))await writeInstance(actor,entry.instanceID,{project:entry.projectID,label:'Nordlicht Küche · Shop & Produktverwaltung',adminURL:entry.cmsURL,schemaName:'nordlicht_kueche',providerProjectID:entry.vercelProjectID,provider:'vercel',template:'custom',payloadVersion:'4.0.0-canary.37',status:'active',notes:'Fiktiver Testbetrieb: deutscher Demo-Shop, Produktverwaltung, Medien, Varianten, Extras und simulierte Bestellungen. Kein Versand, keine Bezahlung.'},true);console.log(JSON.stringify(entry));
}finally{await payload.destroy();await db.end();await closeSnowflakePool();}
