/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LexicalNodes_1FDD23E7".
 */
export type LexicalNodes_1FDD23E7 =
  | SerializedTextNode
  | SerializedTabNode
  | SerializedLineBreakNode
  | SerializedParagraphNode<LexicalNodes_1FDD23E7>
  | SerializedHorizontalRuleNode
  | SerializedUploadNode<'media'>
  | SerializedQuoteNode<LexicalNodes_1FDD23E7>
  | SerializedRelationshipNode<
      | 'users'
      | 'tenants'
      | 'sites'
      | 'integrations'
      | 'form-limits'
      | 'landing-pages'
      | 'clients'
      | 'projects'
      | 'website-settings'
      | 'stall-pages'
      | 'stall-settings'
      | 'stall-header'
      | 'stall-footer'
      | 'stall-redirects'
      | 'payload-kv'
      | 'payload-jobs'
      | 'payload-locked-documents'
      | 'payload-preferences'
      | 'payload-migrations'
    >
  | SerializedAutoLinkNode<LexicalNodes_1FDD23E7, LexicalLinkFields>
  | SerializedLinkNode<LexicalNodes_1FDD23E7, LexicalLinkFields>
  | SerializedListNode<LexicalNodes_1FDD23E7>
  | SerializedListItemNode<LexicalNodes_1FDD23E7>
  | SerializedHeadingNode<LexicalNodes_1FDD23E7>;
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LexicalNodes_D8871F33".
 */
export type LexicalNodes_D8871F33 =
  | SerializedTextNode
  | SerializedTabNode
  | SerializedLineBreakNode
  | SerializedParagraphNode<LexicalNodes_D8871F33>
  | SerializedHeadingNode<LexicalNodes_D8871F33, 'h2' | 'h3' | 'h4'>
  | SerializedHorizontalRuleNode
  | SerializedUploadNode<'media'>
  | SerializedQuoteNode<LexicalNodes_D8871F33>
  | SerializedRelationshipNode<
      | 'users'
      | 'tenants'
      | 'sites'
      | 'integrations'
      | 'form-limits'
      | 'landing-pages'
      | 'clients'
      | 'projects'
      | 'website-settings'
      | 'stall-pages'
      | 'stall-settings'
      | 'stall-header'
      | 'stall-footer'
      | 'stall-redirects'
      | 'payload-kv'
      | 'payload-jobs'
      | 'payload-locked-documents'
      | 'payload-preferences'
      | 'payload-migrations'
    >
  | SerializedAutoLinkNode<LexicalNodes_D8871F33, LexicalLinkFields>
  | SerializedLinkNode<LexicalNodes_D8871F33, LexicalLinkFields>
  | SerializedListNode<LexicalNodes_D8871F33>
  | SerializedListItemNode<LexicalNodes_D8871F33>;

export interface Config {
  auth: {
    users: UserAuthOperations;
    integrations: IntegrationAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    tenants: Tenant;
    sites: Site;
    integrations: Integration;
    'form-limits': FormLimit;
    'landing-pages': LandingPage;
    clients: Client;
    projects: Project;
    'website-settings': WebsiteSetting;
    media: Media;
    'stall-pages': StallPage;
    'stall-settings': StallSetting;
    'stall-header': StallHeader;
    'stall-footer': StallFooter;
    'stall-redirects': StallRedirect;
    'stall-forms': StallForm;
    'stall-form-submissions': StallFormSubmission;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    sites: SitesSelect<false> | SitesSelect<true>;
    integrations: IntegrationsSelect<false> | IntegrationsSelect<true>;
    'form-limits': FormLimitsSelect<false> | FormLimitsSelect<true>;
    'landing-pages': LandingPagesSelect<false> | LandingPagesSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'website-settings': WebsiteSettingsSelect<false> | WebsiteSettingsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'stall-pages': StallPagesSelect<false> | StallPagesSelect<true>;
    'stall-settings': StallSettingsSelect<false> | StallSettingsSelect<true>;
    'stall-header': StallHeaderSelect<false> | StallHeaderSelect<true>;
    'stall-footer': StallFooterSelect<false> | StallFooterSelect<true>;
    'stall-redirects': StallRedirectsSelect<false> | StallRedirectsSelect<true>;
    'stall-forms': StallFormsSelect<false> | StallFormsSelect<true>;
    'stall-form-submissions': StallFormSubmissionsSelect<false> | StallFormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'de') | ('en' | 'de')[];
  globals: {
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: 'en' | 'de';
  widgets: {
    collections: CollectionsWidget;
    'collection-query': CollectionQueryWidget;
    activity: ActivityWidget;
  };
  user: User | Integration;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface IntegrationAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'super-admin' | 'member' | 'editor' | 'site-reader';
  tenants?:
    | {
        tenant: number | Tenant;
        role: 'tenant-admin' | 'editor' | 'reader';
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  apiKey?: string | null;
  apiKeyLast4?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  slug: string;
  domain: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites".
 */
export interface Site {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  key: string;
  url: string;
  model: 'landing' | 'portfolio' | 'business';
  active: boolean;
  modules: ('pages' | 'projects' | 'media' | 'faqs' | 'site-settings' | 'forms' | 'redirects')[];
  languages: ('en' | 'de')[];
  defaultLocale: 'en' | 'de';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integrations".
 */
export interface Integration {
  id: number;
  name: string;
  site: number | Site;
  enabled: boolean;
  scopes: ('content:read' | 'forms:submit')[];
  updatedAt: string;
  createdAt: string;
  apiKey?: string | null;
  apiKeyLast4?: string | null;
  apiKeyIndex?: string | null;
  collection: 'integrations';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-limits".
 */
export interface FormLimit {
  id: number;
  key: string;
  hits: number;
  expiresAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-pages".
 */
export interface LandingPage {
  id: number;
  tenant?: (number | null) | Tenant;
  sourceID?: string | null;
  site: number | Site;
  seoTitle: string;
  seoDescription: string;
  contactEmail: string;
  heroTitle: string;
  heroDescription: string;
  heroButton: string;
  heroNote: string;
  conceptTitle: string;
  conceptDescription: string;
  useCases: {
    title: string;
    description: string;
    id?: string | null;
  }[];
  aboutTitle: string;
  aboutDescription: string;
  faqTitle: string;
  faqs: {
    question: string;
    answer: string;
    id?: string | null;
  }[];
  outlookTitle: string;
  outlookDescription: string;
  closingTitle: string;
  closingButton: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  tenant?: (number | null) | Tenant;
  sourceID?: string | null;
  site: number | Site;
  name: string;
  website?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  tenant?: (number | null) | Tenant;
  sourceID?: string | null;
  site: number | Site;
  name: string;
  slug: string;
  client?: (number | null) | Client;
  summary: string;
  /**
   * Separate paragraphs with a blank line. Do not enter HTML.
   */
  description?: string | null;
  image?: (number | null) | Media;
  category:
    | 'Webentwicklung'
    | 'Webapps'
    | 'APIs & Plattformen'
    | 'Cloud & Infrastruktur'
    | 'Developer Experience'
    | 'Open Source';
  technologies?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  website?: string | null;
  repository?: string | null;
  links?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional; enter confirmed dates only.
   */
  period?: string | null;
  projectStatus?: ('unspecified' | 'development' | 'live' | 'completed' | 'archived') | null;
  featured?: boolean | null;
  sortOrder: number;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  tenant?: (number | null) | Tenant;
  sourceID?: string | null;
  site: number | Site;
  alt: string;
  caption?: LexicalRichText<LexicalNodes_1FDD23E7> | null;
  rightsConfirmed?: boolean | null;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "website-settings".
 */
export interface WebsiteSetting {
  id: number;
  tenant?: (number | null) | Tenant;
  sourceID?: string | null;
  site: number | Site;
  name: string;
  owner: string;
  email: string;
  street: string;
  postcode: string;
  city: string;
  country: string;
  phone?: string | null;
  vatID?: string | null;
  businessID?: string | null;
  register?: string | null;
  databaseProvider?: string | null;
  databaseRegion?: string | null;
  logRetention?: string | null;
  mailProvider?: string | null;
  transfers?: string | null;
  legalReviewed?: boolean | null;
  privacyReviewed?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stall-pages".
 */
export interface StallPage {
  id: number;
  tenant?: (number | null) | Tenant;
  sourceID?: string | null;
  site: number | Site;
  title: string;
  slug: string;
  hero: {
    type: 'image' | 'text' | 'none';
    title?: string | null;
    text?: string | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?: {
              relationTo: 'stall-pages';
              value: number | StallPage;
            } | null;
            url?: string | null;
            label: string;
            /**
             * Darstellung
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
  };
  layout: (
    | ServicesBlock
    | FacilitiesBlock
    | ContentBlock
    | MediaBlock
    | GalleryBlock
    | TeamBlock
    | ContactBlock
    | CallToActionBlock
    | FormBlock
  )[];
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesBlock".
 */
export interface ServicesBlock {
  heading: string;
  intro?: string | null;
  items?:
    | {
        title: string;
        text: string;
        price?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'services';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FacilitiesBlock".
 */
export interface FacilitiesBlock {
  heading: string;
  intro?: string | null;
  items?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'facilities';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: LexicalRichText<LexicalNodes_D8871F33> | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'stall-pages';
            value: number | StallPage;
          } | null;
          url?: string | null;
          label: string;
          /**
           * Darstellung
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock".
 */
export interface GalleryBlock {
  heading?: string | null;
  images: (number | Media)[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'gallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TeamBlock".
 */
export interface TeamBlock {
  heading: string;
  intro?: string | null;
  members?:
    | {
        photo?: (number | null) | Media;
        name: string;
        role?: string | null;
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'team';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBlock".
 */
export interface ContactBlock {
  heading?: string | null;
  /**
   * Adresse, Telefon und Stallzeiten werden aus «Betrieb» übernommen.
   */
  text?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contact';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  heading: string;
  text?: string | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'stall-pages';
            value: number | StallPage;
          } | null;
          url?: string | null;
          label: string;
          /**
           * Darstellung
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | StallForm;
  heading?: string | null;
  intro?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stall-forms".
 */
export interface StallForm {
  id: number;
  tenant?: (number | null) | Tenant;
  sourceID?: string | null;
  site: number | Site;
  title: string;
  fields?: (Checkbox | Country | Email | Message | Number | Select | State | Text | Textarea)[] | null;
  submitButtonLabel?: string | null;
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: LexicalRichText<LexicalNodes_1FDD23E7>;
  redirect?: {
    url: string;
  };
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        message?: LexicalRichText<LexicalNodes_1FDD23E7> | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Checkbox".
 */
export interface Checkbox {
  name: string;
  label?: string | null;
  width?: number | null;
  required?: boolean | null;
  defaultValue?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'checkbox';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Country".
 */
export interface Country {
  name: string;
  label?: string | null;
  width?: number | null;
  required?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'country';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Email".
 */
export interface Email {
  name: string;
  label?: string | null;
  width?: number | null;
  required?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'email';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Message".
 */
export interface Message {
  message?: LexicalRichText<LexicalNodes_1FDD23E7> | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'message';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Number".
 */
export interface Number {
  name: string;
  label?: string | null;
  width?: number | null;
  defaultValue?: number | null;
  required?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'number';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Select".
 */
export interface Select {
  name: string;
  label?: string | null;
  width?: number | null;
  defaultValue?: string | null;
  placeholder?: string | null;
  options?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  required?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'select';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "State".
 */
export interface State {
  name: string;
  label?: string | null;
  width?: number | null;
  required?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'state';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Text".
 */
export interface Text {
  name: string;
  label?: string | null;
  width?: number | null;
  defaultValue?: string | null;
  required?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'text';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Textarea".
 */
export interface Textarea {
  name: string;
  label?: string | null;
  width?: number | null;
  defaultValue?: string | null;
  required?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'textarea';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stall-settings".
 */
export interface StallSetting {
  id: number;
  tenant?: (number | null) | Tenant;
  sourceID?: string | null;
  site: number | Site;
  name: string;
  tagline?: string | null;
  street?: string | null;
  city?: string | null;
  phone?: string | null;
  mobile?: string | null;
  email?: string | null;
  mapsUrl?: string | null;
  /**
   * Ein bis zwei Sätze – Standard-Beschreibung für Google und soziale Netzwerke.
   */
  description?: string | null;
  /**
   * Eingeschaltet zeigt die Website nur noch Titel, Text und Kontakt. Der Admin und die Vorschau für eingeloggte Nutzer bleiben erreichbar.
   */
  maintenance?: {
    enabled?: boolean | null;
    title?: string | null;
    text?: string | null;
  };
  hours?:
    | {
        days: ('mo' | 'tu' | 'we' | 'th' | 'fr' | 'sa' | 'su')[];
        open: string;
        close: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stall-header".
 */
export interface StallHeader {
  id: number;
  tenant?: (number | null) | Tenant;
  sourceID?: string | null;
  site: number | Site;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'stall-pages';
            value: number | StallPage;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stall-footer".
 */
export interface StallFooter {
  id: number;
  tenant?: (number | null) | Tenant;
  sourceID?: string | null;
  site: number | Site;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'stall-pages';
            value: number | StallPage;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stall-redirects".
 */
export interface StallRedirect {
  id: number;
  tenant?: (number | null) | Tenant;
  sourceID?: string | null;
  site: number | Site;
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    url?: string | null;
    reference?: {
      relationTo: 'stall-pages';
      value: number | StallPage;
    } | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stall-form-submissions".
 */
export interface StallFormSubmission {
  id: number;
  tenant?: (number | null) | Tenant;
  sourceID?: string | null;
  site: number | Site;
  deliveryStatus: 'pending' | 'sent' | 'failed';
  form: number | StallForm;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        parent?: {
          taskSlug?: ('inline' | 'schedulePublish') | null;
          taskID?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processingUntil?: string | null;
  processingToken?: string | null;
  /**
   * Used for concurrency control. Jobs with the same key are subject to exclusive/supersedes rules.
   */
  concurrencyKey?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'sites';
        value: number | Site;
      } | null)
    | ({
        relationTo: 'integrations';
        value: number | Integration;
      } | null)
    | ({
        relationTo: 'form-limits';
        value: number | FormLimit;
      } | null)
    | ({
        relationTo: 'landing-pages';
        value: number | LandingPage;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'website-settings';
        value: number | WebsiteSetting;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'stall-pages';
        value: number | StallPage;
      } | null)
    | ({
        relationTo: 'stall-settings';
        value: number | StallSetting;
      } | null)
    | ({
        relationTo: 'stall-header';
        value: number | StallHeader;
      } | null)
    | ({
        relationTo: 'stall-footer';
        value: number | StallFooter;
      } | null)
    | ({
        relationTo: 'stall-redirects';
        value: number | StallRedirect;
      } | null)
    | ({
        relationTo: 'stall-forms';
        value: number | StallForm;
      } | null)
    | ({
        relationTo: 'stall-form-submissions';
        value: number | StallFormSubmission;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'integrations';
        value: number | Integration;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'integrations';
        value: number | Integration;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        role?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  apiKey?: T;
  apiKeyLast4?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  domain?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites_select".
 */
export interface SitesSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  key?: T;
  url?: T;
  model?: T;
  active?: T;
  modules?: T;
  languages?: T;
  defaultLocale?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integrations_select".
 */
export interface IntegrationsSelect<T extends boolean = true> {
  name?: T;
  site?: T;
  enabled?: T;
  scopes?: T;
  updatedAt?: T;
  createdAt?: T;
  apiKey?: T;
  apiKeyLast4?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-limits_select".
 */
export interface FormLimitsSelect<T extends boolean = true> {
  key?: T;
  hits?: T;
  expiresAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-pages_select".
 */
export interface LandingPagesSelect<T extends boolean = true> {
  tenant?: T;
  sourceID?: T;
  site?: T;
  seoTitle?: T;
  seoDescription?: T;
  contactEmail?: T;
  heroTitle?: T;
  heroDescription?: T;
  heroButton?: T;
  heroNote?: T;
  conceptTitle?: T;
  conceptDescription?: T;
  useCases?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  aboutTitle?: T;
  aboutDescription?: T;
  faqTitle?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  outlookTitle?: T;
  outlookDescription?: T;
  closingTitle?: T;
  closingButton?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  tenant?: T;
  sourceID?: T;
  site?: T;
  name?: T;
  website?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  tenant?: T;
  sourceID?: T;
  site?: T;
  name?: T;
  slug?: T;
  client?: T;
  summary?: T;
  description?: T;
  image?: T;
  category?: T;
  technologies?:
    | T
    | {
        name?: T;
        id?: T;
      };
  website?: T;
  repository?: T;
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  period?: T;
  projectStatus?: T;
  featured?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "website-settings_select".
 */
export interface WebsiteSettingsSelect<T extends boolean = true> {
  tenant?: T;
  sourceID?: T;
  site?: T;
  name?: T;
  owner?: T;
  email?: T;
  street?: T;
  postcode?: T;
  city?: T;
  country?: T;
  phone?: T;
  vatID?: T;
  businessID?: T;
  register?: T;
  databaseProvider?: T;
  databaseRegion?: T;
  logRetention?: T;
  mailProvider?: T;
  transfers?: T;
  legalReviewed?: T;
  privacyReviewed?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  tenant?: T;
  sourceID?: T;
  site?: T;
  alt?: T;
  caption?: T;
  rightsConfirmed?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stall-pages_select".
 */
export interface StallPagesSelect<T extends boolean = true> {
  tenant?: T;
  sourceID?: T;
  site?: T;
  title?: T;
  slug?: T;
  hero?:
    | T
    | {
        type?: T;
        title?: T;
        text?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        services?: T | ServicesBlockSelect<T>;
        facilities?: T | FacilitiesBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
        team?: T | TeamBlockSelect<T>;
        contact?: T | ContactBlockSelect<T>;
        cta?: T | CallToActionBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesBlock_select".
 */
export interface ServicesBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  items?:
    | T
    | {
        title?: T;
        text?: T;
        price?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FacilitiesBlock_select".
 */
export interface FacilitiesBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  items?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock_select".
 */
export interface GalleryBlockSelect<T extends boolean = true> {
  heading?: T;
  images?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TeamBlock_select".
 */
export interface TeamBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  members?:
    | T
    | {
        photo?: T;
        name?: T;
        role?: T;
        text?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBlock_select".
 */
export interface ContactBlockSelect<T extends boolean = true> {
  heading?: T;
  text?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  heading?: T;
  text?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  heading?: T;
  intro?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stall-settings_select".
 */
export interface StallSettingsSelect<T extends boolean = true> {
  tenant?: T;
  sourceID?: T;
  site?: T;
  name?: T;
  tagline?: T;
  street?: T;
  city?: T;
  phone?: T;
  mobile?: T;
  email?: T;
  mapsUrl?: T;
  description?: T;
  maintenance?:
    | T
    | {
        enabled?: T;
        title?: T;
        text?: T;
      };
  hours?:
    | T
    | {
        days?: T;
        open?: T;
        close?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stall-header_select".
 */
export interface StallHeaderSelect<T extends boolean = true> {
  tenant?: T;
  sourceID?: T;
  site?: T;
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stall-footer_select".
 */
export interface StallFooterSelect<T extends boolean = true> {
  tenant?: T;
  sourceID?: T;
  site?: T;
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stall-redirects_select".
 */
export interface StallRedirectsSelect<T extends boolean = true> {
  tenant?: T;
  sourceID?: T;
  site?: T;
  from?: T;
  to?:
    | T
    | {
        type?: T;
        url?: T;
        reference?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stall-forms_select".
 */
export interface StallFormsSelect<T extends boolean = true> {
  tenant?: T;
  sourceID?: T;
  site?: T;
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stall-form-submissions_select".
 */
export interface StallFormSubmissionsSelect<T extends boolean = true> {
  tenant?: T;
  sourceID?: T;
  site?: T;
  deliveryStatus?: T;
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  meta?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        parent?:
          | T
          | {
              taskSlug?: T;
              taskID?: T;
            };
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processingUntil?: T;
  processingToken?: T;
  concurrencyKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: number;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collection-query_widget".
 */
export interface CollectionQueryWidget {
  data?: {
    title?: string | null;
    relatedCollection:
      | 'users'
      | 'tenants'
      | 'sites'
      | 'integrations'
      | 'landing-pages'
      | 'clients'
      | 'projects'
      | 'website-settings'
      | 'media'
      | 'stall-pages'
      | 'stall-settings'
      | 'stall-header'
      | 'stall-footer'
      | 'stall-redirects'
      | 'stall-forms'
      | 'stall-form-submissions';
    where?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    sortField?: string | null;
    sortDirection?: ('asc' | 'desc') | null;
    limit?: number | null;
  };
  width: 'x-small' | 'small' | 'medium' | 'large' | 'x-large' | 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity_widget".
 */
export interface ActivityWidget {
  data?: {
    excludedCollections?:
      | (
          | 'users'
          | 'tenants'
          | 'sites'
          | 'integrations'
          | 'landing-pages'
          | 'clients'
          | 'projects'
          | 'website-settings'
          | 'media'
          | 'stall-pages'
          | 'stall-settings'
          | 'stall-header'
          | 'stall-footer'
          | 'stall-redirects'
          | 'stall-forms'
          | 'stall-form-submissions'
        )[]
      | null;
  };
  width: 'x-small' | 'small' | 'medium' | 'large' | 'x-large' | 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'stall-pages';
      value: number | StallPage;
    } | null;
    global?: string | null;
    user?:
      | ({
          relationTo: 'users';
          value: number | User;
        } | null)
      | ({
          relationTo: 'integrations';
          value: number | Integration;
        } | null);
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}

/** @internal Core Lexical types — see @payloadcms/richtext-lexical. */
export type LexicalElementFormat = 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
export type LexicalElementDirection = ('ltr' | 'rtl') | null;

export interface SerializedLexicalElementBase<TChildren> {
  children: TChildren[];
  direction: LexicalElementDirection;
  format: LexicalElementFormat;
  indent: number;
  textFormat?: number;
  textStyle?: string;
  version: number;
}

export type LexicalTextMode = 'normal' | 'token' | 'segmented';

export interface SerializedTextNode {
  type: 'text';
  detail: number;
  format: number;
  mode: LexicalTextMode;
  style: string;
  text: string;
  version: number;
}

export interface SerializedTabNode {
  type: 'tab';
  detail: number;
  format: number;
  mode: LexicalTextMode;
  style: string;
  text: string;
  version: number;
}

export interface SerializedLineBreakNode {
  type: 'linebreak';
  version: number;
}

export interface SerializedParagraphNode<TChildren> extends SerializedLexicalElementBase<TChildren> {
  type: 'paragraph';
  textFormat: number;
  textStyle: string;
}

export interface SerializedHorizontalRuleNode {
  type: 'horizontalrule';
  version: number;
}

export type SerializedUploadNode<TSlugs extends keyof Config['collections'], TFields = { [k: string]: unknown }> = {
  type: 'upload';
  format: LexicalElementFormat;
  id: string;
  version: number;
  fields: TFields;
} & {
  [TSlug in TSlugs]: {
    relationTo: TSlug;
    value: Config['collections'][TSlug]['id'] | Config['collections'][TSlug];
  };
}[TSlugs];

export interface SerializedQuoteNode<TChildren> extends SerializedLexicalElementBase<TChildren> {
  type: 'quote';
}

export type SerializedRelationshipNode<TSlugs extends keyof Config['collections']> = {
  type: 'relationship';
  format: LexicalElementFormat;
  version: number;
} & {
  [TSlug in TSlugs]: {
    relationTo: TSlug;
    value: Config['collections'][TSlug]['id'] | Config['collections'][TSlug];
  };
}[TSlugs];

export interface LexicalLinkFields {
  [k: string]: unknown;
  doc?: {
    relationTo: string;
    value: Config['db']['defaultIDType'] | { [k: string]: unknown; id: Config['db']['defaultIDType'] };
  } | null;
  linkType: 'custom' | 'internal';
  newTab: boolean;
  url?: string;
}
export interface SerializedLinkNode<TChildren, TFields = LexicalLinkFields> extends SerializedLexicalElementBase<TChildren> {
  type: 'link';
  fields: TFields;
  id?: string;
}
export interface SerializedAutoLinkNode<TChildren, TFields = LexicalLinkFields> extends SerializedLexicalElementBase<TChildren> {
  type: 'autolink';
  fields: TFields;
}

export interface SerializedListNode<TChildren> extends SerializedLexicalElementBase<TChildren> {
  type: 'list';
  checked?: boolean;
  listType: 'number' | 'bullet' | 'check';
  start: number;
  tag: 'ul' | 'ol';
}

export interface SerializedListItemNode<TChildren> extends SerializedLexicalElementBase<TChildren> {
  type: 'listitem';
  checked?: boolean;
  value: number;
}

export interface SerializedHeadingNode<
  TChildren,
  TTag extends 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' = 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6',
> extends SerializedLexicalElementBase<TChildren> {
  type: 'heading';
  tag: TTag;
}

/** Shape of a Lexical `richText` field. */
export interface LexicalRichText<TNode> {
  root: {
    children: TNode[];
    direction: LexicalElementDirection;
    format: LexicalElementFormat;
    indent: number;
    type: 'root';
    version: number;
  };
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}