import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Privacy — Webdock Studio',
  description: 'How Webdock handles account, customer, tenant and Vercel integration data.',
  alternates: { canonical: '/privacy' },
  openGraph: { title: 'Privacy — Webdock Studio', url: '/privacy' },
};

export default function Privacy() {
  return <article>
    <p className="subtle-label">Webdock Studio · Updated 4 October 2026</p>
    <h1>Privacy notice</h1>
    <p>This notice covers Webdock account and tenant management, the private Webdock Studio Vercel integration and these public information pages. It does not replace privacy information for independently operated customer websites or Vercel’s own service.</p>
    <h2>Who is responsible</h2>
    <p>Dominik Spitzli, trading as Spitzli Development, is responsible for this processing. For privacy questions, access or deletion requests, email <a href="mailto:dominik@spitzli.dev">dominik@spitzli.dev</a>. Where project data is processed on behalf of a customer, the customer’s instructions and applicable data-processing agreement also apply.</p>
    <h2>Customer profiles, accounts and invitations</h2>
    <p>An operator creates a customer profile containing the customer’s display name and, where provided, person or company names, contact person, email, telephone and postal address. These details support administration of the customer relationship and its projects. Authorised members can view their own tenant profile; tenant administrators can update it and invite people. Internal operator notes are not available in the customer portal.</p>
    <p>Accounts are invitation-only. We process names, email addresses, invitation status, tenant membership and assigned roles to provide the requested access. Authentication records include password hashes, registered passkey public-key information, configured second-factor information and session records. Account and permission changes are recorded for security and accountability. A contact email in a customer profile does not itself create an account or grant access.</p>
    <p>Account invitations and security messages are sent through turboSMTP using the recipient’s email address and the message contents, which may include time-limited account-setup links.</p>
    <h2>Vercel data we receive and why</h2>
    <p>When an authorised operator connects Vercel, Vercel supplies an access token, team identifier and installation identifier. We store these together with the connecting operator’s identifier and connection time. The token is encrypted before database storage and is used on the server to authenticate API requests.</p>
    <p>For selected projects, we read project identifiers and names, framework and runtime settings, deployment identifiers, status, URLs and timestamps, production release information, Git branch names, commit identifiers and messages, and domain names, redirects and verification status. Names and commit messages can contain personal information supplied by members of your team. The source is your connected Vercel account. These details let Studio show hosting status alongside its project records.</p>
    <p>Studio stores project mappings and records connection, disconnection and mapping changes in its audit log, including the acting operator, affected record and action. Retrieved hosting snapshots are fetched for display rather than stored as a deployment-history database. The integration does not request environment-variable values, source-code contents, billing data or Vercel account passwords.</p>
    <h2>Tenant Mail</h2>
    <p>When an operator enables a tenant’s Mail account, Webdock sends the entered account email, first and last name, assigned sending IP and generated account credential to turboSMTP to provision that subaccount. Webdock stores the tenant-to-provider mapping, encrypted credential, account status, limits and usage returned by the provider. Master provider keys are encrypted and are not shown to customers. Provisioning and account changes are audited.</p>
    <p>Domain entries contain the requested domain, a random ownership token and verification timestamps. To check ownership, Webdock queries the public TXT record through Cloudflare’s public DNS-over-HTTPS resolver. The domain name is sent to that resolver; account passwords and provider keys are not. DNS ownership verification is distinct from registration and sending-domain verification at the mail provider.</p>
    <p>When requested by an authorised tenant administrator, sender and tracking domain names are registered with turboSMTP and their verification status is retrieved. Administrators explicitly control open and click tracking; enabling those features lets the provider record recipient opens and link clicks for that tenant’s sending activity. Webdock stores the selected tracking settings and domain verification state.</p>
    <p>Authorised administrators can create and revoke SMTP/API keys for their tenant. A newly created key secret is shown once. Webdock displays the provider’s key labels, permissions, creation dates and IP restrictions; secrets are not retained in local key metadata or audit records.</p>
    <p>Mail mappings and domain records remain until removed through the applicable administration process or a deletion request. Removing a local domain entry does not remove DNS records or a provider-side registration; removing stored master credentials does not revoke that key at the provider.</p>
    <h2>Legal bases</h2>
    <p>We process data needed to provide an agreed service under Article 6(1)(b) GDPR where you are the contracting party. Administration of team access, hosting visibility and security auditing rely on our legitimate interests in operating a secure project-management service under Article 6(1)(f). Where a legal obligation requires retention or disclosure, Article 6(1)(c) applies. Connecting Vercel grants technical access; it is not blanket consent to unrelated processing.</p>
    <h2>Hosting, recipients and international processing</h2>
    <p>Vercel provides hosting and the connected API; Neon provides the PostgreSQL database used to store integration records. Authorised Webdock operators can access the integration’s project information. Data is not sold or used by this integration for advertising or automated decisions with legal or similarly significant effects.</p>
    <p>These providers operate internationally, including in the United States. An EU application region does not mean all support, network or service processing stays in the EU. Their published transfer safeguards and subprocessors are described in <a href="https://vercel.com/legal/dpa">Vercel’s data-processing addendum</a> and <a href="https://neon.com/pdf/DPA.pdf">Neon’s data-processing agreement</a>. Contact us for information about safeguards applicable to your project.</p>
    <h2>Cookies and technical requests</h2>
    <p>The connection flow uses a secure, HTTP-only cookie lasting up to ten minutes to bind the Vercel callback to the operator who started it. Studio also requires an authenticated Webdock session. These cookies support authentication and protect against request forgery. These public pages store an explicitly selected colour theme in your browser’s local storage and load fonts locally.</p>
    <p>Serving requests entails processing technical data such as IP address, requested URL, timestamp and browser information for delivery, fault diagnosis and abuse prevention. Hosting providers may retain technical logs under their service settings and policies. See <a href="https://vercel.com/legal/privacy-notice">Vercel’s privacy notice</a> for its own processing.</p>
    <h2>Retention and disconnection</h2>
    <p>Customer profiles and memberships are retained while needed for the customer relationship and its administration. Archiving a tenant or disabling an account restricts access but does not itself erase the records. Request correction or deletion through the contact above; necessary legal retention and unresolved contractual or security matters are assessed before erasure. Authentication sessions expire after eight hours; account security settings and credentials remain until replaced or removed.</p>
    <p>The stored Vercel credential remains until the connection is replaced or disconnected. Disconnecting in Studio deletes that credential from the active database. It does not uninstall the integration at Vercel: revoke that separately in Vercel’s integration settings. Project mappings remain until removed with the project or through an administrative deletion request.</p>
    <p>Audit records remain available for security investigations and accountability; disconnection does not automatically erase them. Retention depends on the continuing security purpose, applicable contractual or legal requirements and any unresolved claims. Deletion requests are assessed against those needs. Provider backups and technical logs follow their separate retention lifecycles and are not immediately erased by disconnecting.</p>
    <h2>Your choices and rights</h2>
    <p>Connecting Vercel is optional; without it, Studio cannot display live Vercel information. You can restrict the projects selected during installation and revoke access at Vercel.</p>
    <p>Subject to the applicable conditions, you can request access, correction, erasure, restriction and portability of your personal data, and object to processing based on legitimate interests. You can complain to a data-protection supervisory authority, including where you live or work. Contact us using the email above; we may need to verify your identity before disclosing account data. The <a href="https://europa.eu/youreurope/citizens/consumers/internet-telecoms/data-protection-online-privacy/index_en.htm">EU’s information on data-protection rights</a> explains these rights further.</p>
  </article>;
}
