import assert from 'node:assert/strict';
import test from 'node:test';
import crypto from 'node:crypto';
import {getPayload} from 'payload';
import config from '../src/payload.config';
import {landingDefaults} from '../src/cms/landing';
import {previewToken} from '../src/api/preview';

const origin=process.env.TEST_BASE_URL||'http://localhost:3105';
test('archived unified CMS enforces tenant, site, module, membership and integration boundaries',{skip:process.env.LEGACY_CMS_INTEGRATION_TEST!=='1'},async()=>{
 const p=await getPayload({config});const suffix=crypto.randomBytes(5).toString('hex');
 const tenants:number[]=[],sites:number[]=[],users:number[]=[],integrations:number[]=[],pages:number[]=[],clients:number[]=[],projects:number[]=[];
 const key=()=>crypto.randomBytes(32).toString('hex');const editorKey=key(),readerKey=key(),siteKey=key(),portfolioKey=key(),legacyKey=key(),managerKey=key();
 const headers=(token:string,kind='users')=>({'Content-Type':'application/json',Authorization:`${kind} API-Key ${token}`});
 const request=(path:string,token:string,method='GET',data?:unknown,kind='users')=>fetch(origin+'/api/'+path,{method,headers:headers(token,kind),...(data?{body:JSON.stringify(data)}:{})});
 try{
  for(const name of ['a','b'])tenants.push((await p.create({collection:'tenants',overrideAccess:true,data:{name,slug:`test-${name}-${suffix}`,domain:`${name}.example.com`}})).id);
  for(const [i,model] of ['landing','portfolio','portfolio'].entries())sites.push((await p.create({collection:'sites',overrideAccess:true,data:{tenant:tenants[i===2?1:0],name:`Site ${i}`,key:`test-${i}-${suffix}`,url:`https://site-${i}.example.com`,model:model as 'landing'|'portfolio',modules:model==='landing'?['pages','faqs']:['projects','media','site-settings'],languages:['en','de'],defaultLocale:'en',active:true}})).id);
  pages.push((await p.create({collection:'landing-pages',overrideAccess:true,data:{...landingDefaults,site:sites[0],tenant:tenants[0]}})).id);
  for(const [role,apiKey] of [['editor',editorKey],['reader',readerKey]] as const)users.push((await p.create({collection:'users',overrideAccess:true,data:{email:`${role}-${suffix}@example.com`,password:key(),role:'member',apiKey,tenants:[{tenant:tenants[0],role}]}})).id);
  users.push((await p.create({collection:'users',overrideAccess:true,data:{email:`legacy-${suffix}@example.com`,password:key(),role:'site-reader',apiKey:legacyKey,tenants:[{tenant:tenants[0],role:'reader'}]}})).id);
  assert.ok([403,404].includes((await request('projects?draft=true',legacyKey)).status));
  users.push((await p.create({collection:'users',overrideAccess:true,data:{email:`manager-${suffix}@example.com`,password:key(),role:'member',apiKey:managerKey,tenants:[{tenant:tenants[0],role:'tenant-admin'},{tenant:tenants[1],role:'reader'}]}})).id);
  await request(`sites/${sites[0]}`,managerKey,'PATCH',{name:'Managed site',tenant:tenants[1],modules:['projects']});
  const managed = await p.findByID({collection:'sites',id:sites[0],overrideAccess:true,depth:0});
  assert.equal(managed.name,'Managed site');assert.equal(managed.tenant,tenants[0]);assert.deepEqual(managed.modules,['pages','faqs']);
  for(const [site,apiKey] of [[sites[0],siteKey],[sites[1],portfolioKey]] as const)integrations.push((await p.create({collection:'integrations',overrideAccess:true,data:{name:'test '+suffix,site,enabled:true,scopes:['content:read'],apiKey}})).id);
  const list=await request('landing-pages?depth=0',siteKey,'GET',undefined,'integrations');assert.equal(list.status,200);assert.deepEqual((await list.json()).docs.map((d:{id:number})=>d.id),pages);
  assert.ok([401,403].includes((await request('payload-preferences',siteKey,'GET',undefined,'integrations')).status));
  assert.ok([401,403].includes((await request('payload-locked-documents',siteKey,'GET',undefined,'integrations')).status));
  assert.ok([401,403].includes((await request('globals/payload-jobs-stats',siteKey,'GET',undefined,'integrations')).status));
  assert.ok([401,403].includes((await request('payload-jobs/run',siteKey,'GET',undefined,'integrations')).status));
  assert.ok([401,403].includes((await request('tenants',siteKey,'GET',undefined,'integrations')).status));
  assert.ok([401,403,404].includes((await request(`users/${users[0]}`,siteKey,'GET',undefined,'integrations')).status));
  assert.equal((await request(`content/v1/sites/test-2-${suffix}/projects`,portfolioKey,'GET',undefined,'integrations')).status,403);
  assert.ok([403,404].includes((await request(`users/${users[0]}`,siteKey,'PATCH',{role:'super-admin'},'integrations')).status));
  assert.ok([403,404].includes((await request(`landing-pages/${pages[0]}`,siteKey,'PATCH',{heroNote:'forbidden'},'integrations')).status));
  assert.equal((await request(`landing-pages/${pages[0]}`,editorKey,'PATCH',{heroNote:'Editor update'})).status,200);
  assert.ok([403,404].includes((await request(`landing-pages/${pages[0]}`,readerKey,'PATCH',{heroNote:'forbidden'})).status));
  await request(`users/${users[0]}`,editorKey,'PATCH',{role:'super-admin',tenants:[{tenant:tenants[1],role:'tenant-admin'}]});
  const editor=await p.findByID({collection:'users',id:users[0],overrideAccess:true,depth:0});assert.equal(editor.role,'member');assert.deepEqual(editor.tenants?.map(t=>[t.tenant,t.role]),[[tenants[0],'editor']]);
  for(const site of [sites[1],sites[2]])clients.push((await p.create({collection:'clients',overrideAccess:true,data:{name:'test',site,tenant:site===sites[1]?tenants[0]:tenants[1]}})).id);
  const projectData={name:'Test project',slug:`test-${suffix}`,summary:'Published summary',category:'Webentwicklung' as const,sortOrder:1,site:sites[1],tenant:tenants[0],client:clients[0],_status:'published' as const};
  projects.push((await p.create({collection:'projects',overrideAccess:true,locale:'en',data:projectData})).id);
  projects.push((await p.create({collection:'projects',overrideAccess:true,locale:'en',data:{...projectData,slug:`draft-${suffix}`,_status:'draft'}})).id);
  const published=await request(`content/v1/sites/test-1-${suffix}/projects?locale=en`,portfolioKey,'GET',undefined,'integrations');assert.equal(published.status,200);assert.deepEqual((await published.json()).map((d:{id:number})=>d.id),[projects[0]]);
  assert.ok([403,404].includes((await request(`projects/${projects[1]}?draft=true`,portfolioKey,'GET',undefined,'integrations')).status));
  const versions = await request('projects/versions?depth=0', editorKey);
  assert.equal(versions.status, 200);
  for (const version of (await versions.json()).docs) assert.equal(version.version.site, sites[1]);
  assert.ok([403,404].includes((await request('projects/versions', portfolioKey, 'GET', undefined, 'integrations')).status));
  assert.equal((await request(`projects/${projects[0]}`,editorKey,'PATCH',{client:clients[1]})).status,400);
  assert.equal((await request(`content/v1/sites/test-1-${suffix}/projects/draft-${suffix}?previewToken=bad`,portfolioKey,'GET',undefined,'integrations')).status,403);
  const preview=previewToken(`test-1-${suffix}`,`draft-${suffix}`);
  assert.equal((await request(`content/v1/sites/test-1-${suffix}/projects/draft-${suffix}?previewToken=${preview}`,portfolioKey,'GET',undefined,'integrations')).status,200);
  await p.update({collection:'sites',id:sites[1],overrideAccess:true,data:{modules:['media']}});
  assert.equal((await request(`content/v1/sites/test-1-${suffix}/projects`,portfolioKey,'GET',undefined,'integrations')).status,404);
  assert.ok([403,404].includes((await request('projects',portfolioKey,'GET',undefined,'integrations')).status));
  assert.ok([403,404].includes((await request('users/unlock',siteKey,'POST',{email:'nobody@example.com'},'integrations')).status));
 }finally{
  for(const id of projects)await p.delete({collection:'projects',id,overrideAccess:true});
  for(const id of clients)await p.delete({collection:'clients',id,overrideAccess:true});
  for(const id of pages)await p.delete({collection:'landing-pages',id,overrideAccess:true});
  for(const id of integrations)await p.delete({collection:'integrations',id,overrideAccess:true});
  for(const id of users)await p.delete({collection:'users',id,overrideAccess:true});
  for(const id of sites)await p.delete({collection:'sites',id,overrideAccess:true});
  for(const id of tenants)await p.delete({collection:'tenants',id,overrideAccess:true});
  await p.destroy();
 }
});
